### ISSUE TITLE
Feature request: Make WR positions editable

### ISSUE THREAD

**Issue by nohal** [seandepagnier/weather_routing_pi#138]
WAS: ~~Editable field for Start and End in Configuration properties~~
~~Is the editable combo box really intended? It seems that the only effect the editing has is the relation to the position is lost...~~
(And there does not seem to be a way to edit the name or coordinates of an existing weather routing position)

**Comment by seandepagnier** [comment]
It's possible to specify names before the positions are created, or to delete positions that are used in a configuration.

What do you suggest it do in those situations?

**Comment by nohal** [comment]
If the editable combo has no function (or really only a function to break stuff), I would replace the editable combo with a wxChoice.

As per edititng a position, why not allowing editing it (there already is a dialog to be used for that, now invoked only by Position -> New position menu)?

**Comment by seandepagnier** [comment]
So the choices available are, all the positions, as well as the
deleted position if it was deleted?

It's possible to "edit" positions by making a new position with the
same name to replace it.  This works from the context menu on the
chart also.

Maybe it would be nice to integrate directly with waypoints in
opencpn.  They need some sort of flag to mark them as weather routing
waypoints, otherwise the choice/combo will be littered.

**Comment by nohal** [comment]
Maybe, but now my problem simply is I have two positions - "1" and "2". But in the configuration dialog, I can start writing to the Start/End fields. And if I write "nonexistent something", it is considered valid, propagated to the configuration list, and the configuration is unusable (State Invalid Start/End). Which is probably not correct, at least I think - What is the use case for letting me break the configuration like this?
