### ISSUE TITLE
Boat configuration Windows is poorly sized

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#35]
I have just downloaded the latest version of the plugin (March 5th) from Pavel.
While it does work the Boat/Plot configuration windows is completely out of size (see screen capture file).
Boat/SailPlan also has the same issue but less acute.

![weatherrouting-20160316-2115](https://cloud.githubusercontent.com/assets/1193120/13827779/94fc1e78-ebbe-11e5-861e-2d1e668a14ce.jpg)
 
Compared to the release provided with 4.0 I can see that the vertical navigation bar has gone. But the size was already not correct in 4.0.

Regards

Dominig

**Comment by rgleason** [comment]
Dominig,  Yes, I've noticed this too for Windows.  There appears to be a change in the formatting for some reason, perhaps how wxWidgets now uses the formatting commands. I tried to figure it out with wxFormBuilder but was unable.  The formatting is highly nested and I had a suspicion that some of the nested commands were out of sync with what is required now.  (Keep in mind this may be completely wrong.)  At any rate I hoped Sean would be able to fix it, but he headed out again I think. Jon Gough was having some fun with wxForm too so he may know something more. Sorry I can't help.   You are doing a great job getting these all going under your OS. 

PS: It would be really nice if we could get this formatted or if someone who knows could advise how to we could format it. That is a skill I would like to have.

**Comment by rgleason** [comment]
Dominig, the new weather_routing for Opencpn v4.4 has an entirely new interface, so perhaps this should be closed?

**Comment by seandepagnier** [comment]
Anyone thinks the windows in the current git version are the wrong size?

**Comment by rgleason** [comment]
Sean, 
The first Wx_route window is resizeable. and remembered after closing and shutdown of Opencpn.
The second Config window (double click on a config) is not resizeable, but is fine for me, it's postion is remembered.
The Boat ... path to boat.xml files is fine.
The Boat "Edit"  Boat.xml window is adjustiible both ways and is remembered including position. Its size and flexibility is good.

The only thing I might say is the Crossover Tab bottom middle dropdown, words are not all there.
Could this be shortened in accord with our "Definitions" started in weather_routing documentation?
AWD/?  = apparent wind direction/?
TWD/? = True wind direction/?
etc.?

Also I don't seem to have anything on the screen under Crossover, is that future?
Also What does checkbox  "Vert" do? 

I also get it now, you pick a polar and then can see the target boat speeds and angles both upwind and downwind, from the polar.  By going down the list of polars you can see how this changes.
You could have specific polars for various sail configurations, sea state, hull bottom conditions, even motoring, etc.

Then the "Crossover" calculation figures out which is best to use for a given routing location.
When the wind drops to 3 knots, the motor option looks better, so it uses that... What if sailing is slower and that's what you want to use... then don't put the motoring polar in the list.

What does the order of the list determine? Up and down?

Going on to the other window menus, the View menus look very interesting and they appear to be a good size. 

Configuration is basically commands, plus one of the main menus.
Postion is commands basically.
Help goes to the website help, which needs HELP because it is now out of date.

Looks good to me except for the few things I mentioned above.

**Comment by dominig** [comment]
Please feel free to close it. I am not in position to run test now, but if bugs are found on the new code, we will open new bugs.
It make tracking far simpler than keeping old bugs open.
So, I close it.
Thanks.

Dominig
